apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-bs
  name: customer-bs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-bs
  template:
    metadata:
      labels:
        app: customer-bs
    spec:
      containers:
      - name: customer-bs
        image: kevinondock/bank1-customer-bs
        ports:
        - containerPort: 9001
        env:
        - name: PORT
          value: "9001"
        - name: FRONT_WAS_ADDR
          value: "front-was:8081"
        - name: FIN_COMPLEX_ADDR
          value: "customer-bs:8082"
        - name : MCI_GW_ADDR
          value: "mci-gw:8083"
        - name: EAI_GW_ADDR
          value: "eai-gw:8084"
        - name: CORE_1_ADDR
          value: "core-1:8085"
        - name: CUSTOMER_BS_ADDR
          value: "customer-bs:9001"
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "bsdb1"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-bs
spec:
  type: ClusterIP
  selector:
    app: customer-bs
  ports:
  - name: grpc
    port: 9001
    targetPort: 9001