apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fin-complex
  name: fin-complex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-complex
  template:
    metadata:
      labels:
        app: fin-complex
    spec:
      containers:
      - name: fin-complex
        image: kevinondock/bank1-fin-complex
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: FRONT_WAS_ADDR
          value: "front-was:8081"
        - name: FIN_COMPLEX_ADDR
          value: "fin-complex:8082"
        - name : MCI_GW_ADDR
          value: "mci-gw:8083"
        - name: EAI_GW_ADDR
          value: "eai-gw:8084"
        - name: CORE_1_ADDR
          value: "core-1:8085"
        - name: CUSTOMER_BS_ADDR
          value: "customer-bs:9001"
---
apiVersion: v1
kind: Service
metadata:
  name: fin-complex
spec:
  type: ClusterIP
  selector:
    app: fin-complex
  ports:
  - name: grpc
    port: 8082
    targetPort: 8082