apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mci-gw
  name: mci-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mci-gw
  template:
    metadata:
      labels:
        app: mci-gw
    spec:
      containers:
      - name: mci-gw
        image: kevinondock/bank1-mci-gw
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: FRONT_WAS_ADDR
          value: "front-was:8081"
        - name: FIN_COMPLEX_ADDR
          value: "fin-complex:8082"
        - name : MCI_GW_ADDR
          value: "mci-gw:8083"
        - name: EAI_GW_ADDR
          value: "eai-gw:8084"
        - name: CORE_1_ADDR
          value: "core-1:8085"
        - name: CUSTOMER_BS_ADDR
          value: "customer-bs:9001"
---
apiVersion: v1
kind: Service
metadata:
  name: mci-gw
spec:
  type: ClusterIP
  selector:
    app: mci-gw
  ports:
  - name: grpc
    port: 8083
    targetPort: 8083