# apiVersion: v1
# data:
#   DB_Password: am9obmFobg==
# kind: Secret
# metadata:
#   creationTimestamp: null
#   name: db-secret
# --- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  # volumeMode: Filesystem
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: mysqlstorage
  hostPath:
   path: /mysql/mysql_data
  # claimRef:
  #  name: mysql-pvc
  #  namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  # namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: mysqlstorage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    visualize: "true"
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
    # - protocol: TCP
    #   port: 3306
    #   targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.4
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
            # valueFrom:
            #   secretKeyRef:
            #     name: db-secret
            #     key: DB_Password
          # - name: MYSQL_DATABASE
          #   value: myapp
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
         claimName: mysql-pvc
